CREATE DATABASE IF NOT EXISTS FFTCGDB;

USE FFTCGDB;

CREATE TABLE IF NOT EXISTS `Flag`(
	FlagID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS `Type`(
	TypeID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS `Element`(
	ElementID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS `Deck`(
	DeckID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS `Effekt`(
	EffektID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`TEXT` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `Job`(
	JobID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS `Set`(
	SetID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(25) NOT NULL,
	opus_nummer INT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS Karte (
	KartenID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	TypeID INT UNSIGNED NOT NULL,
	CONSTRAINT fk_karte_type FOREIGN KEY (TypeID) REFERENCES `Type`(TypeID),
	JobID INT UNSIGNED,
	CONSTRAINT fk_karte_job FOREIGN KEY(JobID) REFERENCES `Job`(JobID),
	SetID INT UNSIGNED,
	CONSTRAINT fk_karte_set FOREIGN KEY(SetID) REFERENCES `Set`(SetID),
	name VARCHAR(25) NOT NULL,
	`Power` INT UNSIGNED,
	Serial_Type VARCHAR(2) NOT NULL,
	Category VARCHAR(5) NOT NULL,
	Serial_Nr CHAR(3) NOT NULL,
	CONSTRAINT uq_karte_code UNIQUE (Serial_Type, Serial_Nr, SetID)
);

CREATE TABLE IF NOT EXISTS KartenElement(
	KEleID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	KartenID INT UNSIGNED NOT NULL,
	CONSTRAINT fk_KE_KartenID FOREIGN KEY(KartenID) REFERENCES karte(KartenID),
	ElementID INT UNSIGNED NOT NULL,
	CONSTRAINT fk_KE_Element FOREIGN KEY(ElementID) REFERENCES `Element`(ElementID),
	CONSTRAINT uq_karte_element UNIQUE (KartenID, ElementID)
);

CREATE TABLE IF NOT EXISTS KartenKosten(
	KKID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	anzahl INT UNSIGNED NOT NULL,
	KartenID INT UNSIGNED NOT NULL,
	CONSTRAINT fk_KK_KartenID FOREIGN KEY(KartenID) REFERENCES karte(KartenID),
	ElementID INT UNSIGNED NOT NULL,
	CONSTRAINT fk_KK_Element FOREIGN KEY(ElementID) REFERENCES `Element`(ElementID),
	CONSTRAINT uq_kK_element UNIQUE (KartenID, ElementID)
);

CREATE TABLE IF NOT EXISTS KartenFlag(
	KFID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	KartenID INT UNSIGNED NOT NULL,
	CONSTRAINT fk_KF_KartenID FOREIGN KEY(KartenID) REFERENCES karte(KartenID),
	FlagID INT UNSIGNED NOT NULL,
	CONSTRAINT fk_KF_FlagID FOREIGN KEY(FlagID) REFERENCES `flag`(FlagID),
	CONSTRAINT uq_Karte_Flag UNIQUE (KartenID, FlagID)
);

CREATE TABLE IF NOT EXISTS KartenEffekt(
	KEID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	KartenID INT UNSIGNED NOT NULL,
	CONSTRAINT fk_KEf_KartenID FOREIGN KEY(KartenID) REFERENCES karte(KartenID),
	EffektID INT UNSIGNED NOT NULL,
	CONSTRAINT fk_KEf_EffektID FOREIGN KEY(EffektID) REFERENCES `Effekt`(EffektID),
	CONSTRAINT uq_Karte_Effekt UNIQUE (KartenID, EffektID)
);

CREATE TABLE IF NOT EXISTS DeckKarte(
	DKID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	anzahl INT UNSIGNED NOT NULL,
	KartenID INT UNSIGNED NOT NULL,
	CONSTRAINT fk_Deckkarte_KarteID FOREIGN KEY(KartenID) REFERENCES karte(KartenID),
	DeckID INT UNSIGNED NOT NULL,
	CONSTRAINT fk_Deckkarte_DeckID FOREIGN KEY(DeckID) REFERENCES `Deck`(DeckID),
	CONSTRAINT uq_karte_deck UNIQUE (KartenID, DeckID)
);











